spring:
  datasource:
    url: jdbc:mysql://localhost:3306/line_cafe?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: haha
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true

  # 옵션: 콘솔에서 SQL 이쁘게 보이도록 설정
  output:
    ansi:
      enabled: always
